/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package internalversion

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	samples "knative.dev/sample-controller/pkg/apis/samples"
	clientsetinternalversion "knative.dev/sample-controller/pkg/client/clientset/internalversion"
	internalinterfaces "knative.dev/sample-controller/pkg/client/informers/internalversion/internalinterfaces"
	internalversion "knative.dev/sample-controller/pkg/client/listers/samples/internalversion"
)

// AddressableServiceInformer provides access to a shared informer and lister for
// AddressableServices.
type AddressableServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.AddressableServiceLister
}

type addressableServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAddressableServiceInformer constructs a new informer for AddressableService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAddressableServiceInformer(client clientsetinternalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAddressableServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAddressableServiceInformer constructs a new informer for AddressableService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAddressableServiceInformer(client clientsetinternalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Samples().AddressableServices(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Samples().AddressableServices(namespace).Watch(options)
			},
		},
		&samples.AddressableService{},
		resyncPeriod,
		indexers,
	)
}

func (f *addressableServiceInformer) defaultInformer(client clientsetinternalversion.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAddressableServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *addressableServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&samples.AddressableService{}, f.defaultInformer)
}

func (f *addressableServiceInformer) Lister() internalversion.AddressableServiceLister {
	return internalversion.NewAddressableServiceLister(f.Informer().GetIndexer())
}
