/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "knative.dev/sample-controller/pkg/apis/samples/v1alpha1"
)

// AddressableServiceLister helps list AddressableServices.
// All objects returned here must be treated as read-only.
type AddressableServiceLister interface {
	// List lists all AddressableServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AddressableService, err error)
	// AddressableServices returns an object that can list and get AddressableServices.
	AddressableServices(namespace string) AddressableServiceNamespaceLister
	AddressableServiceListerExpansion
}

// addressableServiceLister implements the AddressableServiceLister interface.
type addressableServiceLister struct {
	listers.ResourceIndexer[*v1alpha1.AddressableService]
}

// NewAddressableServiceLister returns a new AddressableServiceLister.
func NewAddressableServiceLister(indexer cache.Indexer) AddressableServiceLister {
	return &addressableServiceLister{listers.New[*v1alpha1.AddressableService](indexer, v1alpha1.Resource("addressableservice"))}
}

// AddressableServices returns an object that can list and get AddressableServices.
func (s *addressableServiceLister) AddressableServices(namespace string) AddressableServiceNamespaceLister {
	return addressableServiceNamespaceLister{listers.NewNamespaced[*v1alpha1.AddressableService](s.ResourceIndexer, namespace)}
}

// AddressableServiceNamespaceLister helps list and get AddressableServices.
// All objects returned here must be treated as read-only.
type AddressableServiceNamespaceLister interface {
	// List lists all AddressableServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AddressableService, err error)
	// Get retrieves the AddressableService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.AddressableService, error)
	AddressableServiceNamespaceListerExpansion
}

// addressableServiceNamespaceLister implements the AddressableServiceNamespaceLister
// interface.
type addressableServiceNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.AddressableService]
}
