/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	samples "knative.dev/sample-controller/pkg/apis/samples"
)

// FakeAddressableServices implements AddressableServiceInterface
type FakeAddressableServices struct {
	Fake *FakeSamples
	ns   string
}

var addressableservicesResource = schema.GroupVersionResource{Group: "samples.knative.dev", Version: "", Resource: "addressableservices"}

var addressableservicesKind = schema.GroupVersionKind{Group: "samples.knative.dev", Version: "", Kind: "AddressableService"}

// Get takes name of the addressableService, and returns the corresponding addressableService object, and an error if there is any.
func (c *FakeAddressableServices) Get(name string, options v1.GetOptions) (result *samples.AddressableService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(addressableservicesResource, c.ns, name), &samples.AddressableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samples.AddressableService), err
}

// List takes label and field selectors, and returns the list of AddressableServices that match those selectors.
func (c *FakeAddressableServices) List(opts v1.ListOptions) (result *samples.AddressableServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(addressableservicesResource, addressableservicesKind, c.ns, opts), &samples.AddressableServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &samples.AddressableServiceList{ListMeta: obj.(*samples.AddressableServiceList).ListMeta}
	for _, item := range obj.(*samples.AddressableServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested addressableServices.
func (c *FakeAddressableServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(addressableservicesResource, c.ns, opts))

}

// Create takes the representation of a addressableService and creates it.  Returns the server's representation of the addressableService, and an error, if there is any.
func (c *FakeAddressableServices) Create(addressableService *samples.AddressableService) (result *samples.AddressableService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(addressableservicesResource, c.ns, addressableService), &samples.AddressableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samples.AddressableService), err
}

// Update takes the representation of a addressableService and updates it. Returns the server's representation of the addressableService, and an error, if there is any.
func (c *FakeAddressableServices) Update(addressableService *samples.AddressableService) (result *samples.AddressableService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(addressableservicesResource, c.ns, addressableService), &samples.AddressableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samples.AddressableService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAddressableServices) UpdateStatus(addressableService *samples.AddressableService) (*samples.AddressableService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(addressableservicesResource, "status", c.ns, addressableService), &samples.AddressableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samples.AddressableService), err
}

// Delete takes name of the addressableService and deletes it. Returns an error if one occurs.
func (c *FakeAddressableServices) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(addressableservicesResource, c.ns, name), &samples.AddressableService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAddressableServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(addressableservicesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &samples.AddressableServiceList{})
	return err
}

// Patch applies the patch and returns the patched addressableService.
func (c *FakeAddressableServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *samples.AddressableService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(addressableservicesResource, c.ns, name, data, subresources...), &samples.AddressableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samples.AddressableService), err
}
