/*
Copyright 2025 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "knative.dev/sample-controller/pkg/apis/samples/v1alpha1"
	samplesv1alpha1 "knative.dev/sample-controller/pkg/client/clientset/versioned/typed/samples/v1alpha1"
)

// fakeSimpleDeployments implements SimpleDeploymentInterface
type fakeSimpleDeployments struct {
	*gentype.FakeClientWithList[*v1alpha1.SimpleDeployment, *v1alpha1.SimpleDeploymentList]
	Fake *FakeSamplesV1alpha1
}

func newFakeSimpleDeployments(fake *FakeSamplesV1alpha1, namespace string) samplesv1alpha1.SimpleDeploymentInterface {
	return &fakeSimpleDeployments{
		gentype.NewFakeClientWithList[*v1alpha1.SimpleDeployment, *v1alpha1.SimpleDeploymentList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("simpledeployments"),
			v1alpha1.SchemeGroupVersion.WithKind("SimpleDeployment"),
			func() *v1alpha1.SimpleDeployment { return &v1alpha1.SimpleDeployment{} },
			func() *v1alpha1.SimpleDeploymentList { return &v1alpha1.SimpleDeploymentList{} },
			func(dst, src *v1alpha1.SimpleDeploymentList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SimpleDeploymentList) []*v1alpha1.SimpleDeployment {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SimpleDeploymentList, items []*v1alpha1.SimpleDeployment) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
